version: "3"
services:
  api:
    image: api:latest
    container_name: api
    command: npm run dev
    volumes:
      - ./src:/home/node/app/src
      - ./package.json:/home/node/app/package.json
      - ./.env:/home/node/app/.env
      - ./.env.example:/home/node/app/.env.example
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      PORT: 9000
    tty: true

  db: 
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    command: --quiet --logpath /dev/null 
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=api-dev
      